### ISSUE TITLE
Unable to build HarfBuzz

### ISSUE THREAD

**Issue by nedley** [unicode-org/text-rendering-tests#14]
```
> python check.py --output report.html --engine CoreText; open report.html
  LIBTOOL-STATIC out/Default/libharfbuzz.a
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: out/Default/obj.target/harfbuzz/src/third_party/harfbuzz/harfbuzz/src/hb-ot-var.o (No such file or directory)
make: *** [out/Default/libharfbuzz.a] Error 1
Traceback (most recent call last):
  File "check.py", line 157, in <module>
    main()
  File "check.py", line 144, in main
    build()
  File "check.py", line 132, in build
    subprocess.check_call(['make', '-s', '--directory', 'build'])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'make', u'-s', u'--directory', u'build']' returned non-zero exit status 2
```

```
dae30870d27d87fa31862b9128dfe25ba3d02758 is the first bad commit
commit dae30870d27d87fa31862b9128dfe25ba3d02758
Author: Sascha Brawer <sascha@brawer.ch>
Date:   Tue Jan 31 08:27:08 2017 +0100

    Update to HarfBuzz 1.4.2

:040000 040000 375bd940eaf86cf0d0e5d922f9692184e74a5936 77351c79b67e5969bf90189a4cbd7499521c7429 M	src

```

**Comment by brawer** [comment]
Hm, it works for me. Maybe your git client is hosed? Try [cloning](https://github.com/unicode-org/text-rendering-tests#text-rendering-tests) into a fresh directory, hopefully that will make it work.

To verify this, and to detect any future broken builds, I’ve [configured](https://github.com/unicode-org/text-rendering-tests/blob/master/.travis.yml) Travis so it compiles the project on both MacOS and Linux whenever there’s a change. The README now shows the build status with a clickable badge:

[![Build Status](https://travis-ci.org/unicode-org/text-rendering-tests.svg?branch=master)](https://travis-ci.org/unicode-org/text-rendering-tests)

**Comment by nedley** [comment]
Indeed, thanks! I’m not sure why git was so confused but a fresh clone built correctly.
